FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

COPY api/PublishOutput .
COPY api/netcoreapp2.0/SkdRefSiteAPI.xml .

FROM base AS final
WORKDIR /app
ENTRYPOINT ["dotnet", "SkdRefSiteAPI.dll"]