version: '3.3'

services:
  angular-ui:
    image: 'refsite-ui'
    build:
      context: .
      dockerfile: Dockerfile-UI
    restart: always
    ports:
      - 80:80
    networks:
      - webnet
  skdrefsiteapi:
    image: skdrefsiteapi
    build:
      context: .
      dockerfile: Dockerfile-API
    restart: always
    ports:
      - 4000:80
    volumes:
      - ./DockerStorage/WebAPI/images:/app/wwwroot/images
    networks:
      - webnet
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: SOME USER
      MONGO_INITDB_ROOT_PASSWORD: SOME PASSWORD
      MONGO_INITDB_DATABASE: skdrefsite
    volumes:
      - ./DockerStorage/mongo/data/db:/data/db
    networks:
      - webnet
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: SOME USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: SOME PASSWORD
      ME_CONFIG_BASICAUTH_USERNAME: SOME USER
      ME_CONFIG_BASICAUTH_PASSWORD: SOME PASSWORD
    networks:
      - webnet
networks:
  webnet:
